from typing import TypeVar, Generic, Union, List, Tuple, Literal, Iterator

Number = Union[float, int]
T = TypeVar("T", bound=Number)

class Position(Generic[T]):
    def __init__(self, *args: T) -> None: ...
    def __setattr__(self, name, value) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Number]: ...
    def __getitem__(self, key: Union[int, Literal["x", "y", "z", "w"]]) -> Number: ...
    @property
    def x(self) -> Number: ...
    @property
    def y(self) -> Number: ...
    @property
    def z(self) -> Number: ...
    @property
    def w(self) -> Number: ...
    @property
    def ndim(self) -> int: ...
    def to_list(self) -> List[Number]: ...
    def to_tuple(self) -> Tuple[Number, ...]: ...
    def is_zero(self) -> bool: ...
    def normalize(self) -> "Position[float]": ...
    def __repr__(self) -> str: ...
